name: Check commits

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check
    steps:
    - uses: actions/checkout@v2.4.0

    - name: Prepare Node
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'

    - name: Install Node packages
      run: npm ci

    - name: Run code linter
      run: npm run format:check
